### ISSUE TITLE
Ethography registre categorie buttons enhancement in user experience. 

### ISSUE THREAD

**Issue by jmarcolan** [EthoWatcher/ethowatcher#18]
Retire o verde escuro dos botões e ponha um verde bem clarinho ou um amarelo claro, que permita ler o nome das categorias. 

Aumente o tamanho das letras. O negrito em letra pequena  cansa e atrapalha o observador.

![image](https://user-images.githubusercontent.com/9295313/124132908-ae869e80-da57-11eb-8d94-ecdac323d297.png)

**Comment by jmarcolan** [comment]
Qual cor deveríamos usar? 
Um dos esquemas de cores (https://color.adobe.com/pt/create/color-wheel) que selecionei foi:
- vermelho ( r= 245; g=91; b=37)
- verde ( r= 123; g=245; b=39)
![image](https://user-images.githubusercontent.com/9295313/125353155-90168200-e338-11eb-82d3-1069c815e512.png)

E o tamanho da letra aumentei para 16px;  O resultado foi os botões como a imagem a baixo, ficou bom ?
 

![image](https://user-images.githubusercontent.com/9295313/125352863-2f874500-e338-11eb-81e4-b73dd7c5a028.png)

**Comment by jmarinoneto-github** [comment]
Este verde estão bom para sinalizar as categorias que NÃO estão em curso. use um LARANJA  (da mesma tonalidade do nosso logotipo) para sinalizar a categoria que está em curso, que está acontecendo
